config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index


  root "main#main"


  get "/login",to: "sessions#new"
  post "/login",to: "sessions#create"
  delete "/logout",to: "sessions#destroy"

  resources :authors
  resources :albums
  resources :events

  resources :tickets


  get "/authors/events/:id",to: "events#myevents"

  post "hello",to: "events#random"


end

app/models/Ticket.rb
class Ticket < ApplicationRecord
  belongs_to :author
  belongs_to :event
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :author
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :albums
  has_many :events

  has_many :tickets

  has_secure_password
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :author
  has_many :tickets
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :check_user,only: [:new]
  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    @album.author_id = current_author.id


    if @album.save
      flash[:notice] = "Album Created!"
      redirect_to current_author
    else
      render "new"
    end
  end

  def edit

  end
  def update

  end
  def destroy
    @album = Album.find(params[:id])

    @album.destroy

    redirect_to
  end
  private
  def album_params
    params.require(:album).permit(:title, :year,:song_count)
  end


  def check_user
    if !logged_in?
      flash[:notice] = "you need to be logged in"
      redirect_to login_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_author, :logged_in?,:check_admin?

  def current_author

    current_author ||= Author.find(session[:author_id]) if session[:author_id]
  end
  def check_admin?
    !!current_author.admin
  end
  def logged_in?
    !!current_author
  end


end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController


  def index

  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params.require(:author).permit(:title,:description,:start_date,:username,:password,:email))

    if @author.save
      redirect_to @author
    else
      render "new"
    end
  end

  def show

  end

  def edit

  end

  def update

  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params.require(:event).permit(
      :title,
      :date,
      :ticket_price,
      :location,
    ))
    @event.author_id = current_author.id

    if @event.save
      redirect_to events_path
    else
      render "new"
    end
  end
  def show

  end
  def index
    @events = Event.all
  end
  def myevents
    @events = Author.find(params[:id]).events
  end
  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:notice] = "Event Canceled!"
    end
  end


  def random
    @currentEvent = Event.find(params[:event])

    # @currentEvent.user_id = current_author.id

    if Ticket.create(event_id: @currentEvent[:id],author_id: current_author.id)
      p "**************saved*************"
      flash[:notice] = "booked!"
      redirect_to events_path
    else
      render "index"
    end

  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def main

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # @author = Author.new
    # flash[:notice] = "hello world"
  end
  def create
    p "******************"

    password = params[:session][:password]
    email = params[:session][:email]

    author = Author.find_by(email: email)



    if author && author.authenticate(password)

      flash[:notice] = "user authenticated"

      session[:author_id] = author.id
      redirect_to author

    else
      render "new",status: :unprocessable_entity
    end

  end

  def destroy

    session[:author_id] = nil

    redirect_to root_path

  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @bookedTickets = Ticket.where(author_id: current_author.id)
  end
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    redirect_to tickets_path
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/albums/index.html.erb
<% if flash[:notice]%>
    <h5 class='text-color flash-msg' style='color: white'><%= flash[:notice]%></h5>
<% end %>

app/views/albums/new.html.erb
<div class='sign-form var2'>
    <%= form_with model: @album do |form| %>
    <h1>Create new Album, Beatch!</h1>
    <div class='row'>
        <div class="col">

            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
            
        </div>

        <div class="col">

            <%= form.label :year %>
            <%= form.number_field :year, class: 'form-control' %>

        </div>
    </div>

    <div class='row'>
        <div class="col">
            <%= form.label :song_count %>
            <%= form.number_field :song_count, class: 'form-control' %>
            
        </div>
    </div>


  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>
<%# 
<form>
  <div class="row">
    <div class="col">
      <input type="text" class="form-control" placeholder="First name">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="Last name">
    </div>
  </div>
</form> %>

app/views/authors/new.html.erb
<div class='sign-form'>
    <%= form_with model: @author do |form| %>
    <h1>Sign up, Beatch!</h1>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.number_field :start_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>


</div>

app/views/authors/show.html.erb
<% if flash[:notice]%>
    <h5 class='text-color flash-msg' style='color: white'><%= flash[:notice]%></h5>
<% end %>


</div>
<div class='albums'>
    <% if current_author.albums %>
        
        <% current_author.albums.each_with_index do |e,i|%>
        <div class='album'>
            <h2><%= e.title%></h2>
            <p>
                Author
                <%= e.author.username%>
            </p>
            <p>Release Year: <%= e.year%></p>
            <p>Songs <%= e.song_count%></p>
            <%= link_to 'Remove Album', album_path(e),data:{turbo_method: :delete} %>
        </div> 
        <% end %>

    <% end %>

</div>

<% if !current_author.albums.any? %>
        <h1 class='text-center mt-5 text-white'>You have no albums</h1>
    <% end %>

app/views/events/index.html.erb
<% if flash[:notice]%>
    <div class='flash-msg'>
        <%= flash[:notice]%>
    </div>
<% end %>


<div class='event-container'>
    <% if @events.any? %>
        <% @events.each do |e|%>
            <div class='event'>
                <h3><%= e.title%> - By <%= e.author.title%></h3>
                <p><strong>location:</strong> <%= e.location%></p>
                <p><strong>date:</strong> <%= e.date%></p>
                <p><strong>price: </strong><%= e.ticket_price%>$</p>
                <% if check_admin? %>
                    <%= button_to "book event", hello_path(event: e),class: "btn btn-success" %>
                <% end %>
            </div>
        <% end %>
    <% else %>
        <h1 class='text-white'>There are no Events</h1>
    <% end %>

</div>

app/views/events/myevents.html.erb
<% if flash[:notice]%>
    <div class='flash-msg'><%= flash[:notice]%></div>
<% end %>
<div class='event-container'>

    <% @events.each do |e|%>
        <div class='event'>
            <h3><%= e.title%> - By <%= e.author.title%></h3>
            <p><strong>location:</strong> <%= e.location%></p>
            <p><strong>date:</strong> <%= e.date ? e.date.day : "" %></p>
            <p><strong>price: </strong><%= e.ticket_price%>$</p>
            <%# <button class='delete-event'>cancle event</button> %>
            <%= link_to 'cancle event',event_path(e),data: {turbo_method: :delete},class: 'delete-event' %>
        </div>
    <% end %>

    <% if !@events.any?%>
        <h1 class='text-white'>You have no Events</h1>
    <% end %>

</div>

app/views/events/new.html.erb
<div class='sign-form var2'>
    <%= form_with model: @event do |form| %>
    <h1>Create new Event, Beatch!</h1>
    <div class='row'>
        <div class="col">

            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
            
        </div>



        <div class="col">

            <%= form.label :ticket_price %>
            <%= form.number_field :ticket_price, class: 'form-control' %>

        </div>

    </div>

    <div class='row'>

        <div class="col">

            <%= form.label :location %>
            <%= form.text_field :location, class: 'form-control' %>

        </div>
          <div class="col w-100 dasdasdcxa">

            <%= form.label :date %>
            <%= form.datetime_field :date, class: 'form-control' %>

        </div>

    </div>

    <div class='row'>
    </div>


  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp10</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "components/nav"%>
   
    <%= yield %>
  </body>
</html>

app/views/main/main.html.erb
 <div class='main-title'>
      <h1>Talk less feel more</h1>
      <p>
        "Melodies dance, emotions soar, rhythms connect; music, a universal language, transcends boundaries, unites souls, echoes feelings."
      </p>
    </div>

app/views/tickets/index.html.erb
<div class='ticket-container'>

<% @bookedTickets.each do |e|%>
    <div class='booked-ticket'>
        <h5><%= e.event.title%></h5>
        <p><%= e.event.date%></p>
        <%= link_to "remove ticket",ticket_path(e.id),class: "btn btn-danger",data: {turbo_method: :delete}
        %>
    </div>
<% end %>
</div>